package template

const TemplateHead = "// DO NOT MODIFY\n// autogenerated by https://github.com/gomponents/gontainer\npackage {{.Input.Meta.Pkg}}\n\n{{range $import := .Imports.GetImports -}}\nimport {{$import.Alias}} \"{{$import.Path}}\"\n{{end}}\n"
